# Generated by Django 5.1.1 on 2024-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="Post",
        ),
    ]
