# Generated by Django 5.1.1 on 2024-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging_app", "0002_rename_post_comment_post"),
    ]

    operations = []
