# Generated by Django 5.1.1 on 2024-09-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging_app", "0003_auto_20240909_1641"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Post",
            new_name="post",
        ),
    ]
